project:
  type: website
  output-dir: docs
  
website:
  title: "Catherine Scipione Forbes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - career.qmd
      - pubs.qmd
    tools:
      - icon: google
        href: https://scholar.google.com.au/citations?user=jm73LccAAAAJ&hl=en
      - icon: github
        href: https://github.com/catherineforbes/mywebsite2
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Catherine Forbes"

format:
  html:
    theme: cerulean
    toc: true

editor: source

