---
title: "Responsibilities"
---


## Current Positions

- Professor, Department of Econometrics and Business Statistics (EBS), Monash University, Melbourne, Australia, since July 2023.	
- Deputy Head, EBS Monash University, since January 2024.  
- Director of Education, EBS Monash University, since January 2025.  
- Adjunct Professor, School of Mathematical Sciences, Sunway University, Selangor, Malaysia, since July 2023.  
- Elected Member, International Statistical Institute, since September 2018.  
- Associate Editor, *Applied Stochastic Models in Business and Industry*, since January 2016.  
- Professional Conduct Committee, International Society for Bayesian Analysis (ISBA), 2021 - 2025.   

## Previous Appointments

- Associate Professor, EBS, Monash University, 2011 - Jun 2023.  
- Adjunct Associate Professor, Sunway University, Nov 2022 - Jun 2023.  
- Senior Lecturer, EBS, Monash University, 2004 - 2010.  
- Lecturer (permanent, part-time), EBS, Monash University, Jul 2001-2003.  
- Lecturer (part-time), EBS, Monash University, 1996 - Jun 2001.  
- Research Fellow, EBS, Monash University, Apr 1993 - 1995.  
- Visiting Professor, Department of Statistics, Ohio State University, Jan - Mar 1993.  
- Visiting Academic, July-Dec, Department of Mathematics, Monash University, Jul - Dec 1992.  
- Statistical Consultant, Procter & Gamble Corporation, Cincinnati, Ohio, Jun - Sep 1988.  

## Other Past Roles

- Director of Graduate Research, EBS Monash University, July 2022 - Dec 2024.  
- Member, Eight Academic Selection Panels (levels B/C/D), EBS Monash University, 2019 - 2025.  
- Member, Academic Selection Panel, Professor (Research), Monash University Malaysia, School of Business, 2024.  
- Member, External Review Panel for Monash Centre for Quantitative Finance and Investment Strategies (CQFIS), 2024.  
- Chair, ISBA EFaB Section, 2023. (Chair-Elect 2022, Past Chair 2024).  
- Academic Progresss Committee, Monash Business School, Monash University, 2021 - 2022. - Equity, Diversity and Social Inclusion Committee (EDSIC), Monash Business School, Monash University, 2018 - 2022.  
- Vision Statement Working Group, Monash Business School, Monash University, 2020 - 2021.  
- Associate Editor, *Bayesian Analysis*, 2019 - 2021.  
- Secretary, ISBA Economics, Finance and Business (EFaB) Section, 2019 - 2020.  
- Elected Member, ISBA Board, 2017 - 2019.  
- Selection Committee, Business Analytics Prize, ARC Centre of Excellence for Mathematical & Statistical Frontiers, 2016 - 2019.  
- Director of Education, EBS, Monash University, 2014–1016.  
- Member, Faculty Education Committee (FEC), Monash Business School, 2012–2013.  
- Member, Faculty Board, Faculty of Business & Economics, Monash University, 2006–2013.
- Faculty Board (Dean’s Nominee), Faculty of Information Technology, Monash University, 2012.  
- PhD Conflict Investigation Panel, Faculty of Business & Economics, 2012.  
- Alternate Member Faculty Education Committee, Monash Business School, 2010 - 2011.  
- Steering Committee, Forgotten Australians Project, Centre for Excellence in Child and Family Welfare, 2007 - 2008.  
- Book Review Editor, *Australian & New Zealand Journal of Statistics*, 2002 - 2007.  
- Guest Co-Editor, *Children Australia*, 31(3), Special Issue on Young People Leaving Care, 2006.  
- Steering Committee, *Telstra Leaving Care Project*, Centre for Excellence in Child and Family Welfare, 2004 - 2005.  
- Acting Director of Consulting, EBS, Monash University, June - Nov 2002.  
- Deputy Director of Consulting, EBS, Monash University, 2001 - 2002.  


## Conference Organisation

- Scientific Committee, 2024 ISBA Bayesian Nonparametric Networking Workshop, National University of Singapore, [https://bnp-networking2024.github.io/](https://bnp-networking2024.github.io/).  
- Chair, Organizing Committee and Member, Scientific Committee, 2023 ISBA BNP Networking Workshop, Monash University,  [https://www.monash.edu/business/events/past-events/econometrics-and-business-statistics/bayesian-nonparametrics-networking-workshop-bnpnet-2023](https://www.monash.edu/business/events/past-events/econometrics-and-business-statistics/bayesian-nonparametrics-networking-workshop-bnpnet-2023).  
- Co-Chair, Organizing Committee, 2023 Workshop in honour of Professors Donald Poskitt and Gael Martin,  [https://www.monash.edu/business/events/past-events/econometrics-and-business-statistics/2023-workshop-in-honour-of-professors-donald-poskitt-and-gael-martin](https://www.monash.edu/business/events/past-events/econometrics-and-business-statistics/2023-workshop-in-honour-of-professors-donald-poskitt-and-gael-martin).  
- Scientific Committee, 13th ISBA BNP Conference (2022), Puerto Varas, Chile, [https://midas.mat.uc.cl/bnp13/](https://midas.mat.uc.cl/bnp13/).  
- Scientific Committee, 15th CFE Conference (2021), London, UK, [http://www.cfenetwork.org/CFE2021/](http://www.cfenetwork.org/CFE2021/).  
- Scientific Committee, 13th CFE Conference (2019), London, UK, [http://www.cfenetwork.org/CFE2019/](http://www.cfenetwork.org/CFE2019/).  
- Scientific Committee, 12th SoFiE Conference (2019) Shanghai, China, [https://econ.fudan.edu.cn/sofie2019/](https://econ.fudan.edu.cn/sofie2019/).  
- Scientific Committee, 12th ISBA BNP Conference(2019), Oxford, UK, [https://www.stats.ox.ac.uk/bnp12/](https://www.stats.ox.ac.uk/bnp12/).  
- Scientific Committee, 11th SoFiE Conference (2018), Lugano, Switzerland, [http://www.sofie2018.usi.ch/](http://www.sofie2018.usi.ch/).  
- Scientific Committee, 11th CFE Conference (2017), London, UK, [http://www.cfenetwork.org/CFE2017/](http://www.cfenetwork.org/CFE2017/).  
- Scientific Committee, 10th SoFiE Conference (2017), New York, USA, [http://sofie.stern.nyu.edu/conferences](http://sofie.stern.nyu.edu/conferences).  
- Local Committee, 7th Symposium on Econometric Theory and Applications (2014), Melbourne, Australia.  
- Scientific Committee, Econometrics Society Australasian Meeting 2014, Hobart, Tasmania. - Co-Chair, Monash Bayesian Conference (2008), State Library of Victoria, Melbourne, Australia.  
- Co-Chair, Towards Better Outcomes for Young People in State Care (2005), Monash University.  
- Local Committee, Econometrics Society Australasian Meeting 2004, Melbourne, Australia.  
- Co-Chair, Econometrics Conference at Monash (1995), Monash University.
	
